# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8adcf616b83f7496f9956da25268dc45ebf3a507cad0d87e0c71d3b74ee8740e995208cce93e476257297ebd0217169c2c7d0762c64ffa9a52d8214bbe21726c

test:
  secret_key_base: f0c66b5109de430e2c769b2f22a3f9e9bd1f3285781a25c883d5abc91b1aa1602f8463104353bda364e301d443d2afc90006237a69cc9eb5536fdb5eec92ed3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
